In [2]:
import numpy as np

array = np.zeros((2, 1))

print("Массив:")
print(array)

Массив:
[[0.]
 [0.]]


In [ ]:
uniform_array = np.random.rand(2, 1)
print("Массив с равномерным распределением:")
print(uniform_array)
    
normal_array = np.random.randn(2, 1)
print("Массив с нормальным распределением:")
print(normal_array)

Массив с равномерным распределением:
[[0.34336586]
 [0.82666858]]
Массив с нормальным распределением:
[[-0.12316002]
 [ 0.27414533]]


In [20]:
print(f"ndim: {array.ndim}")
print(f"shape: {array.shape}")
print(f"size: {array.size}")
print(f"dtype: {array.dtype}")
print(f"itemsize: {array.itemsize} bytes")

ndim: 2
shape: (2, 1)
size: 2
dtype: float64
itemsize: 8 bytes


In [22]:
def print_array_info(a):
    print(f"Shape: {a.shape}")
    print(f"Dimensions: {a.ndim}")
    print(f"Data type: {a.dtype.name}")
    print(f"Item size: {a.itemsize} bytes")
    print(f"Total elements: {a.size}")

print_array_info(array)

Shape: (2, 1)
Dimensions: 2
Data type: float64
Item size: 8 bytes
Total elements: 2


In [25]:
import pandas as pd

df = pd.read_csv('diabetes_data_numeric.csv')

dtypes = {}
for column in df.columns:
    numpy_type = df[column].to_numpy().dtype
    dtypes[column] = str(numpy_type)

dtypes_df = pd.DataFrame(list(dtypes.items()), columns=['Column', 'Data_Type'])

dtypes_df.to_csv('diabetes_data_types.csv', index=False)

print(dtypes_df)

                Column Data_Type
0                  Age     int64
1               Gender     int64
2             Polyuria     int64
3           Polydipsia     int64
4   sudden weight loss     int64
5             weakness     int64
6           Polyphagia     int64
7       Genital thrush     int64
8      visual blurring     int64
9              Itching     int64
10        Irritability     int64
11     delayed healing     int64
12     partial paresis     int64
13    muscle stiffness     int64
14            Alopecia     int64
15             Obesity     int64
16               class     int64


In [ ]:
df_numeric = df.copy()

df_numeric['Gender'] = np.where(df_numeric['Gender'] == 'Male', 1, 0)

yes_no_columns = ['Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness', 
                  'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching',
                  'Irritability', 'delayed healing', 'partial paresis', 
                  'muscle stiffness', 'Alopecia', 'Obesity']

for col in yes_no_columns:
    df_numeric[col] = np.where(df_numeric[col] == 'Yes', 1, 0)

df_numeric['class'] = np.where(df_numeric['class'] == 'Positive', 1, 0)

print(df_numeric.head())

df_numeric.to_csv('diabetes_data_numeric.csv', index=False)

   Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0   40       1         0           1                   0         1   
1   58       1         0           0                   0         1   
2   41       1         1           0                   0         1   
3   45       1         0           0                   1         1   
4   60       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1 